# coding: utf-8

"""
    CipherRun API

     # CipherRun REST API  A production-ready REST API for CipherRun, a comprehensive TLS/SSL security scanner.  ## Features  - **Asynchronous Scans**: Queue scans and poll for status or use WebSockets for real-time updates - **Certificate Inventory**: Track and monitor SSL/TLS certificates - **Compliance Checking**: Verify configurations against industry standards - **Policy Enforcement**: Define and evaluate custom security policies - **Scan History**: Query historical scan data  ## Authentication  All endpoints (except `/health`) require authentication via API key.  Pass the API key in the `X-API-Key` header:  ``` X-API-Key: your-api-key-here ```  ## Rate Limiting  API requests are rate limited to 100 requests per minute per API key.  ## WebSocket Streaming  Request a 60-second, one-use ticket with `POST /api/v1/scan/{id}/stream-ticket`, then connect to the returned `websocket_url`. API credentials are never accepted in query parameters.  The WebSocket sends JSON progress messages:  ```json {   \"msg_type\": \"progress\",   \"scan_id\": \"uuid\",   \"progress\": 45,   \"stage\": \"testing_ciphers\",   \"timestamp\": \"2025-11-09T12:00:00Z\" } ``` 

    The version of the OpenAPI document: 1.0.0
    Contact: security@cipherrun.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

import warnings
from pydantic import validate_call, Field, StrictFloat, StrictStr, StrictInt
from typing import Any, Dict, List, Optional, Tuple, Union
from typing_extensions import Annotated

from pydantic import Field, StrictBool, StrictStr
from typing import Optional
from typing_extensions import Annotated
from cipherrun_client.models.compliance_check_response import ComplianceCheckResponse

from cipherrun_client.api_client import ApiClient, RequestSerialized
from cipherrun_client.api_response import ApiResponse
from cipherrun_client.rest import RESTResponseType


class ComplianceApi:
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None) -> None:
        if api_client is None:
            api_client = ApiClient.get_default()
        self.api_client = api_client


    @validate_call
    def check_compliance(
        self,
        framework: Annotated[StrictStr, Field(description="Compliance framework (pci-dss-v4, nist-sp800-52r2, etc.)")],
        target: Annotated[Optional[StrictStr], Field(description="Target to check (hostname:port)")] = None,
        format: Annotated[Optional[StrictStr], Field(description="Output format (json, terminal, csv)")] = None,
        detailed: Annotated[Optional[StrictBool], Field(description="Include detailed requirement information")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ComplianceCheckResponse:
        """Check compliance

        Runs a compliance check against a specific framework

        :param framework: Compliance framework (pci-dss-v4, nist-sp800-52r2, etc.) (required)
        :type framework: str
        :param target: Target to check (hostname:port)
        :type target: str
        :param format: Output format (json, terminal, csv)
        :type format: str
        :param detailed: Include detailed requirement information
        :type detailed: bool
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._check_compliance_serialize(
            framework=framework,
            target=target,
            format=format,
            detailed=detailed,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "ComplianceCheckResponse",
            '400': "ApiErrorResponse",
            '404': "ApiErrorResponse",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def check_compliance_with_http_info(
        self,
        framework: Annotated[StrictStr, Field(description="Compliance framework (pci-dss-v4, nist-sp800-52r2, etc.)")],
        target: Annotated[Optional[StrictStr], Field(description="Target to check (hostname:port)")] = None,
        format: Annotated[Optional[StrictStr], Field(description="Output format (json, terminal, csv)")] = None,
        detailed: Annotated[Optional[StrictBool], Field(description="Include detailed requirement information")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[ComplianceCheckResponse]:
        """Check compliance

        Runs a compliance check against a specific framework

        :param framework: Compliance framework (pci-dss-v4, nist-sp800-52r2, etc.) (required)
        :type framework: str
        :param target: Target to check (hostname:port)
        :type target: str
        :param format: Output format (json, terminal, csv)
        :type format: str
        :param detailed: Include detailed requirement information
        :type detailed: bool
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._check_compliance_serialize(
            framework=framework,
            target=target,
            format=format,
            detailed=detailed,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "ComplianceCheckResponse",
            '400': "ApiErrorResponse",
            '404': "ApiErrorResponse",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def check_compliance_without_preload_content(
        self,
        framework: Annotated[StrictStr, Field(description="Compliance framework (pci-dss-v4, nist-sp800-52r2, etc.)")],
        target: Annotated[Optional[StrictStr], Field(description="Target to check (hostname:port)")] = None,
        format: Annotated[Optional[StrictStr], Field(description="Output format (json, terminal, csv)")] = None,
        detailed: Annotated[Optional[StrictBool], Field(description="Include detailed requirement information")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Check compliance

        Runs a compliance check against a specific framework

        :param framework: Compliance framework (pci-dss-v4, nist-sp800-52r2, etc.) (required)
        :type framework: str
        :param target: Target to check (hostname:port)
        :type target: str
        :param format: Output format (json, terminal, csv)
        :type format: str
        :param detailed: Include detailed requirement information
        :type detailed: bool
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._check_compliance_serialize(
            framework=framework,
            target=target,
            format=format,
            detailed=detailed,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "ComplianceCheckResponse",
            '400': "ApiErrorResponse",
            '404': "ApiErrorResponse",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _check_compliance_serialize(
        self,
        framework,
        target,
        format,
        detailed,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[str, Union[str, bytes]] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        if framework is not None:
            _path_params['framework'] = framework
        # process the query parameters
        if target is not None:
            
            _query_params.append(('target', target))
            
        if format is not None:
            
            _query_params.append(('format', format))
            
        if detailed is not None:
            
            _query_params.append(('detailed', detailed))
            
        # process the header parameters
        # process the form parameters
        # process the body parameter


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json', 
                    'text/plain', 
                    'text/csv'
                ]
            )


        # authentication setting
        _auth_settings: List[str] = [
            'api_key'
        ]

        return self.api_client.param_serialize(
            method='GET',
            resource_path='/api/v1/compliance/{framework}',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )


