# coding: utf-8

"""
    CipherRun API

     # CipherRun REST API  A production-ready REST API for CipherRun, a comprehensive TLS/SSL security scanner.  ## Features  - **Asynchronous Scans**: Queue scans and poll for status or use WebSockets for real-time updates - **Certificate Inventory**: Track and monitor SSL/TLS certificates - **Compliance Checking**: Verify configurations against industry standards - **Policy Enforcement**: Define and evaluate custom security policies - **Scan History**: Query historical scan data  ## Authentication  All endpoints (except `/health`) require authentication via API key.  Pass the API key in the `X-API-Key` header:  ``` X-API-Key: your-api-key-here ```  ## Rate Limiting  API requests are rate limited to 100 requests per minute per API key.  ## WebSocket Streaming  Request a 60-second, one-use ticket with `POST /api/v1/scan/{id}/stream-ticket`, then connect to the returned `websocket_url`. API credentials are never accepted in query parameters.  The WebSocket sends JSON progress messages:  ```json {   \"msg_type\": \"progress\",   \"scan_id\": \"uuid\",   \"progress\": 45,   \"stage\": \"testing_ciphers\",   \"timestamp\": \"2025-11-09T12:00:00Z\" } ``` 

    The version of the OpenAPI document: 1.0.0
    Contact: security@cipherrun.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cipherrun_client.models.compliance_check_response import ComplianceCheckResponse

class TestComplianceCheckResponse(unittest.TestCase):
    """ComplianceCheckResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ComplianceCheckResponse:
        """Test ComplianceCheckResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ComplianceCheckResponse`
        """
        model = ComplianceCheckResponse()
        if include_optional:
            return ComplianceCheckResponse(
                disclaimer = '',
                evaluated_at = '',
                framework_id = '',
                framework_name = '',
                framework_version = '',
                requirements = [
                    cipherrun_client.models.requirement_result.RequirementResult(
                        category = '', 
                        id = '', 
                        name = '', 
                        remediation = '', 
                        severity = '', 
                        status = '', 
                        violation_count = 0, 
                        violations = [
                            cipherrun_client.models.violation_detail.ViolationDetail(
                                evidence = '', 
                                message = '', 
                                rule_type = '', )
                            ], )
                    ],
                rule_pack_sha256 = '',
                rule_pack_version = '',
                source_url = '',
                source_version = '',
                status = '',
                summary = cipherrun_client.models.compliance_summary.ComplianceSummary(
                    compliance_percentage = 1.337, 
                    failed = 0, 
                    passed = 0, 
                    total = 0, 
                    warnings = 0, ),
                target = ''
            )
        else:
            return ComplianceCheckResponse(
                disclaimer = '',
                evaluated_at = '',
                framework_id = '',
                framework_name = '',
                framework_version = '',
                status = '',
                summary = cipherrun_client.models.compliance_summary.ComplianceSummary(
                    compliance_percentage = 1.337, 
                    failed = 0, 
                    passed = 0, 
                    total = 0, 
                    warnings = 0, ),
                target = '',
        )
        """

    def testComplianceCheckResponse(self):
        """Test ComplianceCheckResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
