events {}

http {
    server {
        listen 443 ssl;
        ssl_certificate /certs/cert.pem;
        ssl_certificate_key /certs/key.pem;
        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_ciphers HIGH:!aNULL:!MD5;
        return 200 "nginx\n";
    }
}
