use super::{SecurityImpact, TlsExtensionInfo};

pub(super) fn all_extensions() -> Vec<TlsExtensionInfo> {
    vec![
        TlsExtensionInfo {
            id: 0x0000,
            name: "server_name (SNI)".to_string(),
            required: true,
            deprecated: false,
            security_impact: SecurityImpact::Critical,
            description: "Server Name Indication (RFC 6066) - Enables virtual hosting for TLS"
                .to_string(),
            rfc: "RFC 6066".to_string(),
        },
        TlsExtensionInfo {
            id: 0xff01,
            name: "renegotiation_info".to_string(),
            required: true,
            deprecated: false,
            security_impact: SecurityImpact::Critical,
            description: "Secure renegotiation (RFC 5746) - Prevents renegotiation attacks"
                .to_string(),
            rfc: "RFC 5746".to_string(),
        },
        TlsExtensionInfo {
            id: 0x0017,
            name: "extended_master_secret".to_string(),
            required: true,
            deprecated: false,
            security_impact: SecurityImpact::Critical,
            description: "Extended Master Secret (RFC 7627) - Prevents session resumption attacks"
                .to_string(),
            rfc: "RFC 7627".to_string(),
        },
        TlsExtensionInfo {
            id: 0x002b,
            name: "supported_versions".to_string(),
            required: true,
            deprecated: false,
            security_impact: SecurityImpact::Critical,
            description: "Supported TLS versions (RFC 8446) - TLS 1.3 version negotiation"
                .to_string(),
            rfc: "RFC 8446".to_string(),
        },
        TlsExtensionInfo {
            id: 0x0005,
            name: "status_request (OCSP Stapling)".to_string(),
            required: false,
            deprecated: false,
            security_impact: SecurityImpact::High,
            description: "OCSP stapling (RFC 6066) - Certificate revocation checking".to_string(),
            rfc: "RFC 6066".to_string(),
        },
        TlsExtensionInfo {
            id: 0x000d,
            name: "signature_algorithms".to_string(),
            required: true,
            deprecated: false,
            security_impact: SecurityImpact::High,
            description: "Signature algorithms (RFC 5246) - Supported signature schemes"
                .to_string(),
            rfc: "RFC 5246, RFC 8446".to_string(),
        },
        TlsExtensionInfo {
            id: 0x0033,
            name: "key_share".to_string(),
            required: false,
            deprecated: false,
            security_impact: SecurityImpact::High,
            description: "Key share (RFC 8446) - TLS 1.3 key exchange".to_string(),
            rfc: "RFC 8446".to_string(),
        },
        TlsExtensionInfo {
            id: 0x002d,
            name: "psk_key_exchange_modes".to_string(),
            required: false,
            deprecated: false,
            security_impact: SecurityImpact::High,
            description: "PSK key exchange modes (RFC 8446) - TLS 1.3 PSK".to_string(),
            rfc: "RFC 8446".to_string(),
        },
        TlsExtensionInfo {
            id: 0x000a,
            name: "supported_groups (ECC)".to_string(),
            required: false,
            deprecated: false,
            security_impact: SecurityImpact::Medium,
            description: "Supported elliptic curves (RFC 4492, RFC 8422) - ECC curve negotiation"
                .to_string(),
            rfc: "RFC 4492, RFC 8422".to_string(),
        },
        TlsExtensionInfo {
            id: 0x000b,
            name: "ec_point_formats".to_string(),
            required: false,
            deprecated: false,
            security_impact: SecurityImpact::Medium,
            description: "EC point formats (RFC 4492) - Uncompressed point format".to_string(),
            rfc: "RFC 4492".to_string(),
        },
        TlsExtensionInfo {
            id: 0x0010,
            name: "application_layer_protocol_negotiation (ALPN)".to_string(),
            required: false,
            deprecated: false,
            security_impact: SecurityImpact::Medium,
            description: "ALPN (RFC 7301) - Application protocol negotiation (HTTP/2, HTTP/3)"
                .to_string(),
            rfc: "RFC 7301".to_string(),
        },
        TlsExtensionInfo {
            id: 0x0023,
            name: "session_ticket".to_string(),
            required: false,
            deprecated: false,
            security_impact: SecurityImpact::Medium,
            description: "Session tickets (RFC 5077) - Stateless session resumption".to_string(),
            rfc: "RFC 5077".to_string(),
        },
        TlsExtensionInfo {
            id: 0x0012,
            name: "signed_certificate_timestamp (CT)".to_string(),
            required: false,
            deprecated: false,
            security_impact: SecurityImpact::Medium,
            description: "Certificate Transparency (RFC 6962) - SCT for CT logs".to_string(),
            rfc: "RFC 6962".to_string(),
        },
        TlsExtensionInfo {
            id: 0x0001,
            name: "max_fragment_length".to_string(),
            required: false,
            deprecated: false,
            security_impact: SecurityImpact::Low,
            description: "Maximum fragment length (RFC 6066) - Negotiate smaller TLS records"
                .to_string(),
            rfc: "RFC 6066".to_string(),
        },
        TlsExtensionInfo {
            id: 0x0003,
            name: "trusted_ca_keys".to_string(),
            required: false,
            deprecated: false,
            security_impact: SecurityImpact::Low,
            description: "Trusted CA keys (RFC 6066) - Client indicates trusted CAs".to_string(),
            rfc: "RFC 6066".to_string(),
        },
        TlsExtensionInfo {
            id: 0x0004,
            name: "truncated_hmac".to_string(),
            required: false,
            deprecated: false,
            security_impact: SecurityImpact::Low,
            description: "Truncated HMAC (RFC 6066) - Reduce HMAC to 80 bits".to_string(),
            rfc: "RFC 6066".to_string(),
        },
        TlsExtensionInfo {
            id: 0x000f,
            name: "heartbeat".to_string(),
            required: false,
            deprecated: false,
            security_impact: SecurityImpact::Low,
            description: "Heartbeat (RFC 6520) - Keep-alive mechanism (Heartbleed vector!)"
                .to_string(),
            rfc: "RFC 6520".to_string(),
        },
        TlsExtensionInfo {
            id: 0x0015,
            name: "padding".to_string(),
            required: false,
            deprecated: false,
            security_impact: SecurityImpact::Low,
            description: "Padding (RFC 7685) - Pad ClientHello to avoid fragmentation".to_string(),
            rfc: "RFC 7685".to_string(),
        },
        TlsExtensionInfo {
            id: 0x001b,
            name: "compress_certificate".to_string(),
            required: false,
            deprecated: false,
            security_impact: SecurityImpact::Low,
            description: "Certificate compression (RFC 8879) - Compress certificate messages"
                .to_string(),
            rfc: "RFC 8879".to_string(),
        },
        TlsExtensionInfo {
            id: 0x0029,
            name: "pre_shared_key".to_string(),
            required: false,
            deprecated: false,
            security_impact: SecurityImpact::Medium,
            description: "Pre-shared key (RFC 8446) - TLS 1.3 PSK identity".to_string(),
            rfc: "RFC 8446".to_string(),
        },
        TlsExtensionInfo {
            id: 0x002a,
            name: "early_data".to_string(),
            required: false,
            deprecated: false,
            security_impact: SecurityImpact::Medium,
            description: "Early data / 0-RTT (RFC 8446) - TLS 1.3 zero round-trip".to_string(),
            rfc: "RFC 8446".to_string(),
        },
        TlsExtensionInfo {
            id: 0x002c,
            name: "cookie".to_string(),
            required: false,
            deprecated: false,
            security_impact: SecurityImpact::Low,
            description: "Cookie (RFC 8446) - TLS 1.3 HelloRetryRequest statelessness".to_string(),
            rfc: "RFC 8446".to_string(),
        },
        TlsExtensionInfo {
            id: 0x0032,
            name: "supported_groups (FFDHE)".to_string(),
            required: false,
            deprecated: false,
            security_impact: SecurityImpact::Medium,
            description: "Finite field Diffie-Hellman groups (RFC 7919)".to_string(),
            rfc: "RFC 7919".to_string(),
        },
        TlsExtensionInfo {
            id: 0x3374,
            name: "next_protocol_negotiation (NPN)".to_string(),
            required: false,
            deprecated: true,
            security_impact: SecurityImpact::Deprecated,
            description: "NPN (Deprecated) - Replaced by ALPN. Used in SPDY".to_string(),
            rfc: "Draft (never standardized)".to_string(),
        },
        TlsExtensionInfo {
            id: 0x0002,
            name: "client_certificate_url".to_string(),
            required: false,
            deprecated: true,
            security_impact: SecurityImpact::Deprecated,
            description: "Client certificate URL (RFC 6066) - Rarely used".to_string(),
            rfc: "RFC 6066".to_string(),
        },
        TlsExtensionInfo {
            id: 0x0006,
            name: "user_mapping".to_string(),
            required: false,
            deprecated: true,
            security_impact: SecurityImpact::Deprecated,
            description: "User mapping (RFC 4681) - Obsolete".to_string(),
            rfc: "RFC 4681".to_string(),
        },
        TlsExtensionInfo {
            id: 0x0007,
            name: "client_authz".to_string(),
            required: false,
            deprecated: true,
            security_impact: SecurityImpact::Deprecated,
            description: "Client authorization (RFC 5878) - Obsolete".to_string(),
            rfc: "RFC 5878".to_string(),
        },
        TlsExtensionInfo {
            id: 0x0008,
            name: "server_authz".to_string(),
            required: false,
            deprecated: true,
            security_impact: SecurityImpact::Deprecated,
            description: "Server authorization (RFC 5878) - Obsolete".to_string(),
            rfc: "RFC 5878".to_string(),
        },
        TlsExtensionInfo {
            id: 0x000c,
            name: "srp".to_string(),
            required: false,
            deprecated: true,
            security_impact: SecurityImpact::Deprecated,
            description: "SRP (RFC 5054) - Secure Remote Password, rarely used".to_string(),
            rfc: "RFC 5054".to_string(),
        },
        TlsExtensionInfo {
            id: 0x000e,
            name: "use_srtp".to_string(),
            required: false,
            deprecated: false,
            security_impact: SecurityImpact::Low,
            description: "SRTP (RFC 5764) - For DTLS-SRTP (WebRTC)".to_string(),
            rfc: "RFC 5764".to_string(),
        },
    ]
}

pub(super) fn parse_extension_data(extension_id: u16, data: &[u8]) -> String {
    match extension_id {
        0x0000 => format!("SNI data ({} bytes)", data.len()),
        0x0005 => format!("OCSP request ({} bytes)", data.len()),
        0x000a => format!("Supported groups ({} bytes)", data.len()),
        0x000d => format!("Signature algorithms ({} bytes)", data.len()),
        0x0010 => format!("ALPN protocols ({} bytes)", data.len()),
        0x0023 => format!("Session ticket ({} bytes)", data.len()),
        0x002b => format!("Supported versions ({} bytes)", data.len()),
        0x0033 => format!("Key share ({} bytes)", data.len()),
        _ => format!("{} bytes", data.len()),
    }
}
