# coding: utf-8

# flake8: noqa
"""
    CipherRun API

     # CipherRun REST API  A production-ready REST API for CipherRun, a comprehensive TLS/SSL security scanner.  ## Features  - **Asynchronous Scans**: Queue scans and poll for status or use WebSockets for real-time updates - **Certificate Inventory**: Track and monitor SSL/TLS certificates - **Compliance Checking**: Verify configurations against industry standards - **Policy Enforcement**: Define and evaluate custom security policies - **Scan History**: Query historical scan data  ## Authentication  All endpoints (except `/health`) require authentication via API key.  Pass the API key in the `X-API-Key` header:  ``` X-API-Key: your-api-key-here ```  ## Rate Limiting  API requests are rate limited to 100 requests per minute per API key.  ## WebSocket Streaming  Request a 60-second, one-use ticket with `POST /api/v1/scan/{id}/stream-ticket`, then connect to the returned `websocket_url`. API credentials are never accepted in query parameters.  The WebSocket sends JSON progress messages:  ```json {   \"msg_type\": \"progress\",   \"scan_id\": \"uuid\",   \"progress\": 45,   \"stage\": \"testing_ciphers\",   \"timestamp\": \"2025-11-09T12:00:00Z\" } ``` 

    The version of the OpenAPI document: 1.0.0
    Contact: security@cipherrun.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


# import models into model package
from cipherrun_client.models.api_error_response import ApiErrorResponse
from cipherrun_client.models.api_usage_stats import ApiUsageStats
from cipherrun_client.models.certificate_list_response import CertificateListResponse
from cipherrun_client.models.certificate_summary import CertificateSummary
from cipherrun_client.models.compliance_check_response import ComplianceCheckResponse
from cipherrun_client.models.compliance_summary import ComplianceSummary
from cipherrun_client.models.create_credential_request import CreateCredentialRequest
from cipherrun_client.models.credential_secret_response import CredentialSecretResponse
from cipherrun_client.models.credential_view import CredentialView
from cipherrun_client.models.domain_stats import DomainStats
from cipherrun_client.models.health_response import HealthResponse
from cipherrun_client.models.permission import Permission
from cipherrun_client.models.policy_check_result import PolicyCheckResult
from cipherrun_client.models.policy_evaluation_request import PolicyEvaluationRequest
from cipherrun_client.models.policy_evaluation_response import PolicyEvaluationResponse
from cipherrun_client.models.policy_request import PolicyRequest
from cipherrun_client.models.policy_response import PolicyResponse
from cipherrun_client.models.requirement_result import RequirementResult
from cipherrun_client.models.rotate_credential_request import RotateCredentialRequest
from cipherrun_client.models.scan_history_item import ScanHistoryItem
from cipherrun_client.models.scan_history_response import ScanHistoryResponse
from cipherrun_client.models.scan_options import ScanOptions
from cipherrun_client.models.scan_request import ScanRequest
from cipherrun_client.models.scan_response import ScanResponse
from cipherrun_client.models.scan_status import ScanStatus
from cipherrun_client.models.scan_status_response import ScanStatusResponse
from cipherrun_client.models.stats_response import StatsResponse
from cipherrun_client.models.stream_ticket_response import StreamTicketResponse
from cipherrun_client.models.violation_detail import ViolationDetail
