# coding: utf-8

"""
    CipherRun API

     # CipherRun REST API  A production-ready REST API for CipherRun, a comprehensive TLS/SSL security scanner.  ## Features  - **Asynchronous Scans**: Queue scans and poll for status or use WebSockets for real-time updates - **Certificate Inventory**: Track and monitor SSL/TLS certificates - **Compliance Checking**: Verify configurations against industry standards - **Policy Enforcement**: Define and evaluate custom security policies - **Scan History**: Query historical scan data  ## Authentication  All endpoints (except `/health`) require authentication via API key.  Pass the API key in the `X-API-Key` header:  ``` X-API-Key: your-api-key-here ```  ## Rate Limiting  API requests are rate limited to 100 requests per minute per API key.  ## WebSocket Streaming  Request a 60-second, one-use ticket with `POST /api/v1/scan/{id}/stream-ticket`, then connect to the returned `websocket_url`. API credentials are never accepted in query parameters.  The WebSocket sends JSON progress messages:  ```json {   \"msg_type\": \"progress\",   \"scan_id\": \"uuid\",   \"progress\": 45,   \"stage\": \"testing_ciphers\",   \"timestamp\": \"2025-11-09T12:00:00Z\" } ``` 

    The version of the OpenAPI document: 1.0.0
    Contact: security@cipherrun.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List
from typing import Optional, Set
from typing_extensions import Self

class CertificateSummary(BaseModel):
    """
    Certificate summary
    """ # noqa: E501
    common_name: StrictStr = Field(description="Subject common name")
    days_until_expiry: StrictInt = Field(description="Days until expiry")
    fingerprint: StrictStr = Field(description="SHA-256 fingerprint")
    hostnames: List[StrictStr] = Field(description="Associated hostnames")
    is_expired: StrictBool = Field(description="Certificate is expired")
    is_expiring_soon: StrictBool = Field(description="Certificate is expiring soon (< 30 days)")
    issuer: StrictStr = Field(description="Issuer")
    san: List[StrictStr] = Field(description="Subject alternative names")
    valid_from: datetime = Field(description="Valid from")
    valid_until: datetime = Field(description="Valid until")
    __properties: ClassVar[List[str]] = ["common_name", "days_until_expiry", "fingerprint", "hostnames", "is_expired", "is_expiring_soon", "issuer", "san", "valid_from", "valid_until"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CertificateSummary from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CertificateSummary from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "common_name": obj.get("common_name"),
            "days_until_expiry": obj.get("days_until_expiry"),
            "fingerprint": obj.get("fingerprint"),
            "hostnames": obj.get("hostnames"),
            "is_expired": obj.get("is_expired"),
            "is_expiring_soon": obj.get("is_expiring_soon"),
            "issuer": obj.get("issuer"),
            "san": obj.get("san"),
            "valid_from": obj.get("valid_from"),
            "valid_until": obj.get("valid_until")
        })
        return _obj


