# coding: utf-8

"""
    CipherRun API

     # CipherRun REST API  A production-ready REST API for CipherRun, a comprehensive TLS/SSL security scanner.  ## Features  - **Asynchronous Scans**: Queue scans and poll for status or use WebSockets for real-time updates - **Certificate Inventory**: Track and monitor SSL/TLS certificates - **Compliance Checking**: Verify configurations against industry standards - **Policy Enforcement**: Define and evaluate custom security policies - **Scan History**: Query historical scan data  ## Authentication  All endpoints (except `/health`) require authentication via API key.  Pass the API key in the `X-API-Key` header:  ``` X-API-Key: your-api-key-here ```  ## Rate Limiting  API requests are rate limited to 100 requests per minute per API key.  ## WebSocket Streaming  Request a 60-second, one-use ticket with `POST /api/v1/scan/{id}/stream-ticket`, then connect to the returned `websocket_url`. API credentials are never accepted in query parameters.  The WebSocket sends JSON progress messages:  ```json {   \"msg_type\": \"progress\",   \"scan_id\": \"uuid\",   \"progress\": 45,   \"stage\": \"testing_ciphers\",   \"timestamp\": \"2025-11-09T12:00:00Z\" } ``` 

    The version of the OpenAPI document: 1.0.0
    Contact: security@cipherrun.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from cipherrun_client.models.compliance_summary import ComplianceSummary
from cipherrun_client.models.requirement_result import RequirementResult
from typing import Optional, Set
from typing_extensions import Self

class ComplianceCheckResponse(BaseModel):
    """
    Compliance check response
    """ # noqa: E501
    disclaimer: StrictStr = Field(description="Scope limitation for external TLS posture checks")
    evaluated_at: StrictStr = Field(description="Evaluation timestamp")
    framework_id: StrictStr = Field(description="Framework ID")
    framework_name: StrictStr = Field(description="Framework name")
    framework_version: StrictStr = Field(description="Framework version")
    requirements: Optional[List[RequirementResult]] = Field(default=None, description="Detailed requirement results")
    rule_pack_sha256: Optional[StrictStr] = Field(default=None, description="SHA-256 of the exact loaded rule pack YAML")
    rule_pack_version: Optional[StrictStr] = Field(default=None, description="Independently versioned CipherRun rule pack")
    source_url: Optional[StrictStr] = Field(default=None, description="Primary publication URL mapped by this pack")
    source_version: Optional[StrictStr] = Field(default=None, description="Primary publication version mapped by this pack")
    status: StrictStr = Field(description="Overall compliance status")
    summary: ComplianceSummary = Field(description="Compliance summary")
    target: StrictStr = Field(description="Target evaluated")
    __properties: ClassVar[List[str]] = ["disclaimer", "evaluated_at", "framework_id", "framework_name", "framework_version", "requirements", "rule_pack_sha256", "rule_pack_version", "source_url", "source_version", "status", "summary", "target"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ComplianceCheckResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in requirements (list)
        _items = []
        if self.requirements:
            for _item_requirements in self.requirements:
                if _item_requirements:
                    _items.append(_item_requirements.to_dict())
            _dict['requirements'] = _items
        # override the default output from pydantic by calling `to_dict()` of summary
        if self.summary:
            _dict['summary'] = self.summary.to_dict()
        # set to None if rule_pack_sha256 (nullable) is None
        # and model_fields_set contains the field
        if self.rule_pack_sha256 is None and "rule_pack_sha256" in self.model_fields_set:
            _dict['rule_pack_sha256'] = None

        # set to None if rule_pack_version (nullable) is None
        # and model_fields_set contains the field
        if self.rule_pack_version is None and "rule_pack_version" in self.model_fields_set:
            _dict['rule_pack_version'] = None

        # set to None if source_url (nullable) is None
        # and model_fields_set contains the field
        if self.source_url is None and "source_url" in self.model_fields_set:
            _dict['source_url'] = None

        # set to None if source_version (nullable) is None
        # and model_fields_set contains the field
        if self.source_version is None and "source_version" in self.model_fields_set:
            _dict['source_version'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ComplianceCheckResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "disclaimer": obj.get("disclaimer"),
            "evaluated_at": obj.get("evaluated_at"),
            "framework_id": obj.get("framework_id"),
            "framework_name": obj.get("framework_name"),
            "framework_version": obj.get("framework_version"),
            "requirements": [RequirementResult.from_dict(_item) for _item in obj["requirements"]] if obj.get("requirements") is not None else None,
            "rule_pack_sha256": obj.get("rule_pack_sha256"),
            "rule_pack_version": obj.get("rule_pack_version"),
            "source_url": obj.get("source_url"),
            "source_version": obj.get("source_version"),
            "status": obj.get("status"),
            "summary": ComplianceSummary.from_dict(obj["summary"]) if obj.get("summary") is not None else None,
            "target": obj.get("target")
        })
        return _obj


