# coding: utf-8

"""
    CipherRun API

     # CipherRun REST API  A production-ready REST API for CipherRun, a comprehensive TLS/SSL security scanner.  ## Features  - **Asynchronous Scans**: Queue scans and poll for status or use WebSockets for real-time updates - **Certificate Inventory**: Track and monitor SSL/TLS certificates - **Compliance Checking**: Verify configurations against industry standards - **Policy Enforcement**: Define and evaluate custom security policies - **Scan History**: Query historical scan data  ## Authentication  All endpoints (except `/health`) require authentication via API key.  Pass the API key in the `X-API-Key` header:  ``` X-API-Key: your-api-key-here ```  ## Rate Limiting  API requests are rate limited to 100 requests per minute per API key.  ## WebSocket Streaming  Request a 60-second, one-use ticket with `POST /api/v1/scan/{id}/stream-ticket`, then connect to the returned `websocket_url`. API credentials are never accepted in query parameters.  The WebSocket sends JSON progress messages:  ```json {   \"msg_type\": \"progress\",   \"scan_id\": \"uuid\",   \"progress\": 45,   \"stage\": \"testing_ciphers\",   \"timestamp\": \"2025-11-09T12:00:00Z\" } ``` 

    The version of the OpenAPI document: 1.0.0
    Contact: security@cipherrun.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self

class ScanOptions(BaseModel):
    """
    Scan options
    """ # noqa: E501
    analyze_certificates: Optional[StrictBool] = Field(default=False, description="Analyze certificates")
    client_simulation: Optional[StrictBool] = Field(default=False, description="Run client simulations")
    full_scan: Optional[StrictBool] = Field(default=False, description="Run full comprehensive scan")
    ip: Optional[StrictStr] = Field(default=None, description="Specific IP address to test")
    ipv4_only: Optional[StrictBool] = Field(default=False, description="Use IPv4 only")
    ipv6_only: Optional[StrictBool] = Field(default=False, description="Use IPv6 only")
    starttls_protocol: Optional[StrictStr] = Field(default=None, description="STARTTLS protocol (smtp, imap, pop3, etc.)")
    test_ciphers: Optional[StrictBool] = Field(default=False, description="Test all cipher suites")
    test_http_headers: Optional[StrictBool] = Field(default=False, description="Test HTTP security headers")
    test_protocols: Optional[StrictBool] = Field(default=False, description="Test all protocols (SSLv2, SSLv3, TLS 1.0-1.3)")
    test_vulnerabilities: Optional[StrictBool] = Field(default=False, description="Test all vulnerabilities")
    timeout_seconds: Optional[Annotated[int, Field(strict=True, ge=0)]] = Field(default=30, description="Connection and socket timeout in seconds")
    __properties: ClassVar[List[str]] = ["analyze_certificates", "client_simulation", "full_scan", "ip", "ipv4_only", "ipv6_only", "starttls_protocol", "test_ciphers", "test_http_headers", "test_protocols", "test_vulnerabilities", "timeout_seconds"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ScanOptions from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if ip (nullable) is None
        # and model_fields_set contains the field
        if self.ip is None and "ip" in self.model_fields_set:
            _dict['ip'] = None

        # set to None if starttls_protocol (nullable) is None
        # and model_fields_set contains the field
        if self.starttls_protocol is None and "starttls_protocol" in self.model_fields_set:
            _dict['starttls_protocol'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ScanOptions from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "analyze_certificates": obj.get("analyze_certificates") if obj.get("analyze_certificates") is not None else False,
            "client_simulation": obj.get("client_simulation") if obj.get("client_simulation") is not None else False,
            "full_scan": obj.get("full_scan") if obj.get("full_scan") is not None else False,
            "ip": obj.get("ip"),
            "ipv4_only": obj.get("ipv4_only") if obj.get("ipv4_only") is not None else False,
            "ipv6_only": obj.get("ipv6_only") if obj.get("ipv6_only") is not None else False,
            "starttls_protocol": obj.get("starttls_protocol"),
            "test_ciphers": obj.get("test_ciphers") if obj.get("test_ciphers") is not None else False,
            "test_http_headers": obj.get("test_http_headers") if obj.get("test_http_headers") is not None else False,
            "test_protocols": obj.get("test_protocols") if obj.get("test_protocols") is not None else False,
            "test_vulnerabilities": obj.get("test_vulnerabilities") if obj.get("test_vulnerabilities") is not None else False,
            "timeout_seconds": obj.get("timeout_seconds") if obj.get("timeout_seconds") is not None else 30
        })
        return _obj


