# coding: utf-8

"""
    CipherRun API

     # CipherRun REST API  A production-ready REST API for CipherRun, a comprehensive TLS/SSL security scanner.  ## Features  - **Asynchronous Scans**: Queue scans and poll for status or use WebSockets for real-time updates - **Certificate Inventory**: Track and monitor SSL/TLS certificates - **Compliance Checking**: Verify configurations against industry standards - **Policy Enforcement**: Define and evaluate custom security policies - **Scan History**: Query historical scan data  ## Authentication  All endpoints (except `/health`) require authentication via API key.  Pass the API key in the `X-API-Key` header:  ``` X-API-Key: your-api-key-here ```  ## Rate Limiting  API requests are rate limited to 100 requests per minute per API key.  ## WebSocket Streaming  Request a 60-second, one-use ticket with `POST /api/v1/scan/{id}/stream-ticket`, then connect to the returned `websocket_url`. API credentials are never accepted in query parameters.  The WebSocket sends JSON progress messages:  ```json {   \"msg_type\": \"progress\",   \"scan_id\": \"uuid\",   \"progress\": 45,   \"stage\": \"testing_ciphers\",   \"timestamp\": \"2025-11-09T12:00:00Z\" } ``` 

    The version of the OpenAPI document: 1.0.0
    Contact: security@cipherrun.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from cipherrun_client.models.scan_status import ScanStatus
from typing import Optional, Set
from typing_extensions import Self

class ScanResponse(BaseModel):
    """
    Scan response (returned when creating a scan)
    """ # noqa: E501
    estimated_completion: Optional[datetime] = Field(default=None, description="Estimated completion time")
    queued_at: datetime = Field(description="When the scan was queued")
    scan_id: StrictStr = Field(description="Unique scan ID")
    status: ScanStatus = Field(description="Current scan status")
    target: StrictStr = Field(description="Target being scanned")
    websocket_url: Optional[StrictStr] = Field(default=None, description="WebSocket URL for real-time progress")
    __properties: ClassVar[List[str]] = ["estimated_completion", "queued_at", "scan_id", "status", "target", "websocket_url"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ScanResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if estimated_completion (nullable) is None
        # and model_fields_set contains the field
        if self.estimated_completion is None and "estimated_completion" in self.model_fields_set:
            _dict['estimated_completion'] = None

        # set to None if websocket_url (nullable) is None
        # and model_fields_set contains the field
        if self.websocket_url is None and "websocket_url" in self.model_fields_set:
            _dict['websocket_url'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ScanResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "estimated_completion": obj.get("estimated_completion"),
            "queued_at": obj.get("queued_at"),
            "scan_id": obj.get("scan_id"),
            "status": obj.get("status"),
            "target": obj.get("target"),
            "websocket_url": obj.get("websocket_url")
        })
        return _obj


