# coding: utf-8

"""
    CipherRun API

     # CipherRun REST API  A production-ready REST API for CipherRun, a comprehensive TLS/SSL security scanner.  ## Features  - **Asynchronous Scans**: Queue scans and poll for status or use WebSockets for real-time updates - **Certificate Inventory**: Track and monitor SSL/TLS certificates - **Compliance Checking**: Verify configurations against industry standards - **Policy Enforcement**: Define and evaluate custom security policies - **Scan History**: Query historical scan data  ## Authentication  All endpoints (except `/health`) require authentication via API key.  Pass the API key in the `X-API-Key` header:  ``` X-API-Key: your-api-key-here ```  ## Rate Limiting  API requests are rate limited to 100 requests per minute per API key.  ## WebSocket Streaming  Request a 60-second, one-use ticket with `POST /api/v1/scan/{id}/stream-ticket`, then connect to the returned `websocket_url`. API credentials are never accepted in query parameters.  The WebSocket sends JSON progress messages:  ```json {   \"msg_type\": \"progress\",   \"scan_id\": \"uuid\",   \"progress\": 45,   \"stage\": \"testing_ciphers\",   \"timestamp\": \"2025-11-09T12:00:00Z\" } ``` 

    The version of the OpenAPI document: 1.0.0
    Contact: security@cipherrun.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from cipherrun_client.models.scan_status import ScanStatus
from typing import Optional, Set
from typing_extensions import Self

class ScanStatusResponse(BaseModel):
    """
    Scan status response
    """ # noqa: E501
    completed_at: Optional[datetime] = Field(default=None, description="When scan completed")
    current_stage: Optional[StrictStr] = Field(default=None, description="Current stage being executed")
    error: Optional[StrictStr] = Field(default=None, description="Error message if failed")
    eta_seconds: Optional[Annotated[int, Field(strict=True, ge=0)]] = Field(default=None, description="Estimated seconds until completion")
    progress: Annotated[int, Field(strict=True, ge=0)] = Field(description="Progress percentage (0-100)")
    results_url: Optional[StrictStr] = Field(default=None, description="Link to results (if completed)")
    scan_id: StrictStr = Field(description="Unique scan ID")
    started_at: Optional[datetime] = Field(default=None, description="When scan started")
    status: ScanStatus = Field(description="Current status")
    __properties: ClassVar[List[str]] = ["completed_at", "current_stage", "error", "eta_seconds", "progress", "results_url", "scan_id", "started_at", "status"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ScanStatusResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if completed_at (nullable) is None
        # and model_fields_set contains the field
        if self.completed_at is None and "completed_at" in self.model_fields_set:
            _dict['completed_at'] = None

        # set to None if current_stage (nullable) is None
        # and model_fields_set contains the field
        if self.current_stage is None and "current_stage" in self.model_fields_set:
            _dict['current_stage'] = None

        # set to None if error (nullable) is None
        # and model_fields_set contains the field
        if self.error is None and "error" in self.model_fields_set:
            _dict['error'] = None

        # set to None if eta_seconds (nullable) is None
        # and model_fields_set contains the field
        if self.eta_seconds is None and "eta_seconds" in self.model_fields_set:
            _dict['eta_seconds'] = None

        # set to None if results_url (nullable) is None
        # and model_fields_set contains the field
        if self.results_url is None and "results_url" in self.model_fields_set:
            _dict['results_url'] = None

        # set to None if started_at (nullable) is None
        # and model_fields_set contains the field
        if self.started_at is None and "started_at" in self.model_fields_set:
            _dict['started_at'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ScanStatusResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "completed_at": obj.get("completed_at"),
            "current_stage": obj.get("current_stage"),
            "error": obj.get("error"),
            "eta_seconds": obj.get("eta_seconds"),
            "progress": obj.get("progress"),
            "results_url": obj.get("results_url"),
            "scan_id": obj.get("scan_id"),
            "started_at": obj.get("started_at"),
            "status": obj.get("status")
        })
        return _obj


