# coding: utf-8

"""
    CipherRun API

     # CipherRun REST API  A production-ready REST API for CipherRun, a comprehensive TLS/SSL security scanner.  ## Features  - **Asynchronous Scans**: Queue scans and poll for status or use WebSockets for real-time updates - **Certificate Inventory**: Track and monitor SSL/TLS certificates - **Compliance Checking**: Verify configurations against industry standards - **Policy Enforcement**: Define and evaluate custom security policies - **Scan History**: Query historical scan data  ## Authentication  All endpoints (except `/health`) require authentication via API key.  Pass the API key in the `X-API-Key` header:  ``` X-API-Key: your-api-key-here ```  ## Rate Limiting  API requests are rate limited to 100 requests per minute per API key.  ## WebSocket Streaming  Request a 60-second, one-use ticket with `POST /api/v1/scan/{id}/stream-ticket`, then connect to the returned `websocket_url`. API credentials are never accepted in query parameters.  The WebSocket sends JSON progress messages:  ```json {   \"msg_type\": \"progress\",   \"scan_id\": \"uuid\",   \"progress\": 45,   \"stage\": \"testing_ciphers\",   \"timestamp\": \"2025-11-09T12:00:00Z\" } ``` 

    The version of the OpenAPI document: 1.0.0
    Contact: security@cipherrun.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from setuptools import setup, find_packages  # noqa: H301

# To install the library, run the following
#
# python setup.py install
#
# prerequisite: setuptools
# http://pypi.python.org/pypi/setuptools
NAME = "cipherrun-client"
VERSION = "0.4.0"
PYTHON_REQUIRES = ">=3.7"
REQUIRES = [
    "urllib3 >= 1.25.3, < 2.1.0",
    "python-dateutil",
    "pydantic >= 2",
    "typing-extensions >= 4.7.1",
]

setup(
    name=NAME,
    version=VERSION,
    description="CipherRun API",
    author="CipherRun",
    author_email="security@cipherrun.io",
    url="",
    keywords=["OpenAPI", "OpenAPI-Generator", "CipherRun API"],
    install_requires=REQUIRES,
    packages=find_packages(exclude=["test", "tests"]),
    include_package_data=True,
    license="GPL-3.0-or-later",
    long_description_content_type='text/markdown',
    long_description=r"""\
     # CipherRun REST API  A production-ready REST API for CipherRun, a comprehensive TLS/SSL security scanner.  ## Features  - **Asynchronous Scans**: Queue scans and poll for status or use WebSockets for real-time updates - **Certificate Inventory**: Track and monitor SSL/TLS certificates - **Compliance Checking**: Verify configurations against industry standards - **Policy Enforcement**: Define and evaluate custom security policies - **Scan History**: Query historical scan data  ## Authentication  All endpoints (except &#x60;/health&#x60;) require authentication via API key.  Pass the API key in the &#x60;X-API-Key&#x60; header:  &#x60;&#x60;&#x60; X-API-Key: your-api-key-here &#x60;&#x60;&#x60;  ## Rate Limiting  API requests are rate limited to 100 requests per minute per API key.  ## WebSocket Streaming  Request a 60-second, one-use ticket with &#x60;POST /api/v1/scan/{id}/stream-ticket&#x60;, then connect to the returned &#x60;websocket_url&#x60;. API credentials are never accepted in query parameters.  The WebSocket sends JSON progress messages:  &#x60;&#x60;&#x60;json {   \&quot;msg_type\&quot;: \&quot;progress\&quot;,   \&quot;scan_id\&quot;: \&quot;uuid\&quot;,   \&quot;progress\&quot;: 45,   \&quot;stage\&quot;: \&quot;testing_ciphers\&quot;,   \&quot;timestamp\&quot;: \&quot;2025-11-09T12:00:00Z\&quot; } &#x60;&#x60;&#x60; 
    """,  # noqa: E501
    package_data={"cipherrun_client": ["py.typed"]},
)
