use super::{Command, CommandExit, ScanDiffCommand};
use crate::Result;
use crate::scanner::ScanResults;
use crate::vulnerabilities::FindingStatus;
use async_trait::async_trait;
use std::path::PathBuf;

const MAX_OUTPUT_BYTES: usize = 128 * 1024;

pub struct RemediationCommand {
    input: PathBuf,
    format: String,
    output: Option<PathBuf>,
    overwrite: bool,
}

impl RemediationCommand {
    pub fn new(input: PathBuf, format: String, output: Option<PathBuf>, overwrite: bool) -> Self {
        Self {
            input,
            format,
            output,
            overwrite,
        }
    }

    fn render(results: &ScanResults, format: &str) -> Result<String> {
        let format = format.to_ascii_lowercase();
        let findings: Vec<_> = results
            .vulnerabilities
            .iter()
            .filter(|finding| finding.status() == FindingStatus::ConfirmedVulnerable)
            .collect();
        let finding_list = findings
            .iter()
            .map(|finding| format!("CR-TLS-{:?}-001", finding.vuln_type).to_ascii_uppercase())
            .collect::<Vec<_>>()
            .join(", ");
        let header = format!(
            "# Generated by CipherRun {}\n# Target: {}\n# Confirmed findings: {}\n# Review and test before deploying.\n",
            env!("CARGO_PKG_VERSION"),
            results.target,
            if finding_list.is_empty() {
                "none"
            } else {
                &finding_list
            }
        );

        let body = match format.as_str() {
            "nginx" => format!(
                "{header}\nssl_protocols TLSv1.2 TLSv1.3;\nssl_ciphers 'ECDHE+AESGCM:ECDHE+CHACHA20:!aNULL:!eNULL:!MD5:!RC4:!3DES';\nssl_prefer_server_ciphers on;\n"
            ),
            "apache" => format!(
                "{header}\nSSLProtocol -all +TLSv1.2 +TLSv1.3\nSSLCipherSuite ECDHE+AESGCM:ECDHE+CHACHA20:!aNULL:!eNULL:!MD5:!RC4:!3DES\nSSLHonorCipherOrder on\n"
            ),
            "haproxy" => format!(
                "{header}\nssl-default-bind-options ssl-min-ver TLSv1.2\nssl-default-bind-ciphers ECDHE+AESGCM:ECDHE+CHACHA20:!aNULL:!eNULL:!MD5:!RC4:!3DES\nssl-default-bind-ciphersuites TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256:TLS_AES_128_GCM_SHA256\n"
            ),
            "envoy" => format!(
                "{header}\ncommon_tls_context:\n  tls_params:\n    tls_minimum_protocol_version: TLSv1_2\n    cipher_suites:\n      - ECDHE-ECDSA-AES128-GCM-SHA256\n      - ECDHE-RSA-AES128-GCM-SHA256\n      - ECDHE-ECDSA-CHACHA20-POLY1305\n      - ECDHE-RSA-CHACHA20-POLY1305\n"
            ),
            "caddy" => format!(
                "{header}\ntls {{\n    protocols tls1.2 tls1.3\n    ciphers TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256 TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256\n}}\n"
            ),
            _ => {
                return Err(crate::TlsError::InvalidInput {
                    message: "format must be one of: nginx, apache, haproxy, envoy, caddy"
                        .to_string(),
                });
            }
        };

        if body.len() > MAX_OUTPUT_BYTES {
            return Err(crate::TlsError::InvalidInput {
                message: "generated remediation exceeds the output limit".to_string(),
            });
        }
        Ok(body)
    }

    fn write_output(path: &PathBuf, content: &str, overwrite: bool) -> Result<()> {
        if path.exists() && !overwrite {
            return Err(crate::TlsError::InvalidInput {
                message: format!(
                    "output file '{}' already exists; pass --overwrite to replace it",
                    path.display()
                ),
            });
        }
        std::fs::write(path, content).map_err(|source| crate::TlsError::FileSystemError {
            path: path.display().to_string(),
            source,
        })?;
        Ok(())
    }
}

#[async_trait]
impl Command for RemediationCommand {
    async fn execute(&self) -> Result<CommandExit> {
        let results = ScanDiffCommand::read_scan(&self.input)?;
        let content = Self::render(&results, &self.format)?;
        if let Some(path) = &self.output {
            Self::write_output(path, &content, self.overwrite)?;
            println!("Remediation written to {}", path.display());
        } else {
            print!("{content}");
        }
        Ok(CommandExit::success())
    }

    fn name(&self) -> &'static str {
        "RemediationCommand"
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn renders_each_supported_format() {
        let results = ScanResults {
            target: "example.com:443".to_string(),
            ..Default::default()
        };
        for format in ["nginx", "apache", "haproxy", "envoy", "caddy"] {
            let output = RemediationCommand::render(&results, format).expect("format renders");
            assert!(
                output.contains("TLSv1.2")
                    || output.contains("TLSv1_2")
                    || output.contains("tls1.2")
            );
            assert!(output.contains("example.com:443"));
        }
    }

    #[test]
    fn rejects_unknown_format() {
        let results = ScanResults::default();
        let error = RemediationCommand::render(&results, "lighttpd")
            .expect_err("unknown format should fail");
        assert!(error.to_string().contains("format must be one of"));
    }
}
