#[derive(Debug, Clone, Default)]
pub struct ScanRequestVulns {
    pub vulnerabilities: bool,
    pub heartbleed: bool,
    pub no_heartbleed: bool,
    pub ccs: bool,
    pub ticketbleed: bool,
    pub robot: bool,
    pub renegotiation: bool,
    pub no_renegotiation: bool,
    pub crime: bool,
    pub no_compression: bool,
    pub breach: bool,
    pub poodle: bool,
    pub fallback: bool,
    pub no_fallback: bool,
    pub sweet32: bool,
    pub beast: bool,
    pub lucky13: bool,
    pub freak: bool,
    pub logjam: bool,
    pub drown: bool,
    pub early_data: bool,
}
