#!/usr/bin/env bash
# Generate data/debian_blacklist.txt from the g0tmi1k/debian-ssh key corpus.
#
# CVE-2008-0166: Debian OpenSSL (2006-2008) seeded its PRNG from the PID alone,
# so only ~32k distinct keys exist per (type, size, arch). g0tmi1k publishes the
# precomputed private keys; we derive each public SubjectPublicKeyInfo, hash it
# (SHA-256, the fingerprint CipherRun matches on), and emit one per line.
#
# The corpus is ~1GB, so it is NOT vendored; run this offline to (re)populate the
# embedded blacklist, then rebuild — include_str! bakes it into the binary.
#
# ponytail: assumes g0tmi1k ships PEM/OpenSSH private keys openssl can read; if a
# future layout differs, adjust the find/openssl pipe below.
set -euo pipefail

repo="https://github.com/g0tmi1k/debian-ssh"
out="$(cd "$(dirname "$0")/.." && pwd)/data/debian_blacklist.txt"
work="$(mktemp -d)"
trap 'rm -rf "$work"' EXIT

echo "Cloning $repo (large; ~1GB) ..." >&2
git clone --depth 1 "$repo" "$work/src"

echo "Extracting key archives ..." >&2
find "$work/src" -name '*.tar.bz2' -exec tar -xjf {} -C "$work" \;

echo "Deriving SubjectPublicKeyInfo SHA-256 fingerprints ..." >&2
{
  echo "# Debian OpenSSL weak-key blacklist (CVE-2008-0166) — generated by scripts/gen_debian_blacklist.sh"
  echo "# sha256(SubjectPublicKeyInfo DER), lowercase hex, one per line."
  find "$work" -type f ! -name '*.pub' ! -name '*.tar.bz2' -print0 \
    | while IFS= read -r -d '' key; do
        openssl pkey -in "$key" -pubout -outform DER 2>/dev/null \
          | openssl dgst -sha256 2>/dev/null \
          | awk '{print tolower($NF)}'
      done \
    | grep -E '^[0-9a-f]{64}$' \
    | sort -u
} > "$out"

count="$(grep -cE '^[0-9a-f]{64}' "$out" || true)"
echo "Wrote $count fingerprints to $out" >&2
